# Generated by Django 5.1.5 on 2025-01-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
