# Generated by Django 5.1.5 on 2025-01-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_order_cart_order_carts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
