# Generated by Django 5.1.5 on 2025-01-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
